

export const SAMPLE_ACTION = "SAMPLE_ACTION";
export const SIGNUP_ACTION = "SIGNUP_ACTION";
export const SIGNUP_ACTION_FAIL = "SIGNUP_ACTION_FAIL";
export const SIGNUP_ACTION_SUCCESS = "SIGNUP_ACTION_SUCCESS";
export const SIGNUP_ACTION_LOADING = "SIGNUP_ACTION_LOADING";


