export const SAMPLE_ACTION = "SAMPLE_ACTION";
export const SIGNIN_ACTION = "SIGNUP_ACTION";
export const SIGNIN_ACTION_SUCCESS = "SIGNIN_ACTION_SUCCESS";
export const SIGNIN_ACTION_FAIL = "SIGNIN_ACTION_FAIL";
export const SIGNIN_ACTION_LOADING = "SIGNIN_ACTION_LOADING";
export const TOGGLE_SIGNIN = 'TOGGLE_SIGNIN';
export const GOOGLE_SIGNIN_ACTION = 'GOOGLE_SIGNIN_ACTION';
export const GOOGLE_SIGNIN_ACTION_SUCCESS = 'GOOGLE_SIGNIN_ACTION_SUCCESS';
export const GOOGLE_SIGNIN_ACTION_FAIL = 'GOOGLE_SIGNIN_ACTION_FAIL';
export const FACEBOOK_SIGNIN_ACTION = 'FACEBOOK_SIGNIN_ACTION';
export const FACEBOOK_SIGNIN_ACTION_SUCCESS = 'FACEBOOK_SIGNIN_ACTION_SUCCESS';
export const FACEBOOK_SIGNIN_ACTION_FAIL = 'FACEBOOK_SIGNIN_ACTION_FAIL';

export default {
  SAMPLE_ACTION,
  SIGNIN_ACTION,
  SIGNIN_ACTION_SUCCESS,
  SIGNIN_ACTION_FAIL,
  SIGNIN_ACTION_LOADING,
  TOGGLE_SIGNIN,
  GOOGLE_SIGNIN_ACTION,
  GOOGLE_SIGNIN_ACTION_SUCCESS,
  FACEBOOK_SIGNIN_ACTION,
  FACEBOOK_SIGNIN_ACTION_SUCCESS

};
