export const SAMPLE_ACTION = "SAMPLE_ACTION";
export const SIGNIN_ACTION = "SIGNUP_ACTION";
export const SIGNIN_ACTION_SUCCESS = "SIGNIN_ACTION_SUCCESS";
export const SIGNIN_ACTION_FAIL = "SIGNIN_ACTION_FAIL";
export const SIGNIN_ACTION_LOADING = "SIGNIN_ACTION_LOADING";
export const TOGGLE_SIGNIN = 'TOGGLE_SIGNIN'
export default {
  SAMPLE_ACTION,
  SIGNIN_ACTION,
  SIGNIN_ACTION_SUCCESS,
  SIGNIN_ACTION_FAIL,
  SIGNIN_ACTION_LOADING,
  TOGGLE_SIGNIN
};
